name: Black Duck Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  
permissions:
  contents: write

jobs:
  blackducksca:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Check home dir
        run: |
          echo $HOME
          echo ~
      - name: Install detect in this dir
        run: |
          wget -O ~/.bridge/blackduck/detect-10.7.0.jar "https://artifactory.intra.infineon.com/artifactory/gen-repo-blackduck-com/bds-integrations-release/com/blackduck/integration/detect/10.7.0/detect-10.7.0.jar"
          wget -O ~/bridge-cli/bridge-cli-bundle-linux64.zip "https://artifactory.intra.infineon.com/artifactory/gen-repo-blackduck-com/bds-integrations-release/com/blackduck/integration/bridge/binaries/bridge-cli-bundle/latest/bridge-cli-bundle-linux64.zip"
      - name: Unzip cli bundle
        run: unzip -o ~/bridge-cli/bridge-cli-bundle-linux64.zip -d /srv/cirunner/bridge-cli


      - name: Print these dirs
        run: |
          cd ~/bridge-cli/ 
          ls
          cd ~/.bridge/blackduck/
          ls
      - name: Black Duck Security Scan
        id: black-duck-security-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        # env:
        # BRIDGE_DETECT_INSTALL_DIRECTORY: ~/.bridge/blackduck/detect-10.7.0.jar
        # DETECT_BLACKDUCK_SIGNATURE_SCANNER_SNIPPET_MATCHING: SNIPPET_MATCHING
        # DETECT_ACCURACY_REQUIRED: ALL
        # DETECT_PROJECT_VERSION_NAME: comprehensive_snippet_all
        
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          # tool.install.directory: ~/.bridge/blackduck/detect-10.7.0.jar
          
          bridgecli_download_url: https://artifactory.intra.infineon.com/artifactory/gen-repo-blackduck-com/bds-integrations-release/com/blackduck/integration/bridge/binaries/bridge-cli-bundle/latest/bridge-cli-bundle-linux64.zip
          
          BLACKDUCK.DOWNLOAD.URL: https://artifactory.intra.infineon.com/artifactory/gen-repo-blackduck-com/bds-integrations-release/com/blackduck/integration/detect/10.7.0/detect-10.7.0.jar
          
          network_airgap: true
          bridgecli_install_directory: /srv/cirunner/bridge-cli/bridge-cli-bundle-linux64/
          # detect_install_directory: /srv/cirunner/.blackduck/bridge/tools/blackduck-detect/10.6.0/
          detect_install_directory: /srv/cirunner/.bridge/blackduck/
          
          blackducksca_waitForScan: true
          mark_build_status: failure
          include_diagnostics: false          
          blackducksca_prComment_enabled: false
          blackducksca_fixpr_enabled: false
          blackducksca_reports_sarif_create: false
          blackducksca_upload_sarif_report: false

      - name: Remove all dependencies after scan
        run: rm -rf /srv/cirunner/bridge-cli/* /srv/cirunner/.bridge/blackduck/*
